### PR TITLE
Update oc-list-cards.sh

### PR DESCRIPTION
**Pull request by thehappyhippo**
Added full path of lspci to allow execution for regular user

### CODE REVIEW

**Comment by fmoyen** [comment]
I can see (using my own systems) lspci binary is located in /usr/bin for Ubuntu systems (and indeed in /usr/sbin for RHEL systems). This means this request if applied will make o-list-cards.sh not functional on Ubuntu systems. So it needs modifications (like checking the running OS) before applying it to master branch.

**Review by fmoyen — CHANGES_REQUESTED** [review]
I can see (using my own systems) lspci binary is located in /usr/bin for Ubuntu systems (and indeed in /usr/sbin for RHEL systems). This means this request if applied will make o-list-cards.sh not functional on Ubuntu systems. So it needs modifications (like checking the running OS) before applying it to master branch.

**Comment by thehappyhippo** [comment]
Yes you are right. I had a little thought that the path could different between distros, but never checked this. I will put more effort solving this issue.

**Comment by fmoyen** [comment]
Strange you have a user who does not know /usr/sbin path. Is this really normal ?

**Review by fmoyen — APPROVED** [review]

**Comment by fmoyen** [comment]
There is no harm in the requested merge so I validate it. But for information, we will not test in the same way the existence of all system commands used by the tools

**Pull request merged**
